[package]
name = "libswifft"
description = "To be done"
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"

[dependencies]
libswifft_sys = { path = "../libswifft-sys", version = "0.1.0" }
rand = "0.9.0-alpha.1"