[package]
name = "libswifft_sys"
links = "LibSWIFFT"
description = "To be done"
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[build-dependencies]
bindgen = "0.69.0"
cmake = "0.1.0"